spring:
  application:
    name: database
# ?? ?? (localhost:8080/app/database)
server:
  servlet:
    context-path: /app
  port: 8080

# Readinessprobe, Livenessprobe ?
# /app/actuator/health/liveness, /app/actuator/health/readiness
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Database ????
database:
  ip: 10.10.10.1
  port: 1234
  username: dev
  password: dev